project/Project/MVCPresentationTier/Controllers/ChatController.cs
using MVCPresentationTier.ChatServiceReference;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace MVCPresentationTier.Controllers
{
    public class ChatController : Controller, IChatServiceCallback
    {
        public ActionResult GetChats()
        {
            var cookie = Request.Cookies.Get("aCookie");
            if (cookie != null)
            {
                ChatServiceClient client = new ChatServiceClient(new InstanceContext(this));
                int aCookie = Int32.Parse(cookie.Value);
                client.Online(aCookie);
                ViewBag.Chats = client.GetChatsByName("", aCookie);
                ViewBag.SearchBy = "";
                return View();
            }
            else
                return Redirect("/Profile/Login");
        }

        [HttpPost]
        public ActionResult GetChats(FormCollection collection)
        {
            var cookie = Request.Cookies.Get("aCookie");
            if (cookie != null)
            {
                ChatServiceClient client = new ChatServiceClient(new InstanceContext(this));
                int aCookie = Int32.Parse(cookie.Value);
                client.Online(aCookie);
                ViewBag.Chats = client.GetChatsByName(collection["searchBy"], aCookie);
                ViewBag.SearchBy = collection["searchBy"];
                return View();
            }
            else
            {
                return Redirect("/Profile/Login");
            }
        }

        public ActionResult GetChat(int? chatId, int? maxNrOfUsers, String name, int? ownerID, DateTime? time, bool? type)
        {
            Chat chat = new Chat();
            if (!chatId.HasValue)
            {
                chat.ActivityId = 0;
            }
            else
            {
                chat.ActivityId = chatId.Value;
            }
            if (!maxNrOfUsers.HasValue)
            {
                chat.MaxNrOfUsers = 0;
            }
            else
            {
                chat.MaxNrOfUsers = maxNrOfUsers.Value;
            }
            chat.Name = name;
            if (!ownerID.HasValue)
            {
                chat.ProfileId = 0;
            }
            else
            {
                chat.ProfileId = ownerID.Value;
            }
            if (!time.HasValue)
            {
                chat.TimeStamp = new DateTime();
            }
            else
            {
                chat.TimeStamp = time.Value;
            }
            if (!type.HasValue)
            {
                chat.Type = true;
            }
            else
            {
                chat.Type = type.Value;
            }
            return View(chat);
        }

        #region For later
        public void JoinChat(int chatId)
        {
            throw new NotImplementedException();
        }

        public void Notification(Chat chat)
        {
            throw new NotImplementedException();
        }

        public void Refreshed()
        {
            throw new NotImplementedException();
        }
        #endregion
    }
}

project/Project/MVCPresentationTier/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.SignalR;
using System.ServiceModel;
using SignalRChat;

namespace MVCPresentationTier.Controllers
{
    public class MessageController : Controller
    {
        public ActionResult ChatRoom(int? chatId)
        {
            if (chatId.HasValue)
            {
                var cookie = Request.Cookies.Get("aCookie");
                if (cookie != null)
                {
                    ViewBag.ChatId = chatId;
                    ViewBag.ProfileId = Int32.Parse(cookie.Value);
                    return View();
                }
                else
                {
                    return Redirect("/Profile/Login");
                }
            }
            else
            {
                return Redirect("/Chat/GetChats");
            }
        }
    }
}

project/Project/MVCPresentationTier/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCPresentationTier.ProfileServiceReference;

namespace MVCPresentationTier.Controllers
{
    public class ProfileController : Controller
    {
        public ActionResult LogIn()
        {
            if (Request.Cookies.Get("aCookie") == null)
            {
                ViewBag.LoginStatus = -1;
                return View();
            }
            else
            {
                return Redirect("/");
            }
        }
        
        [HttpPost]
        public ActionResult LogIn(FormCollection collection)
        {
            ProfileServiceClient client = new ProfileServiceClient();
            var username = collection["username"];
            var password = collection["password"];
            Profile profile = new Profile
            {
                Username = username,
                Password = password
            };
            var profileId = client.Authenticate(profile);
            ViewBag.LoginStatus = profileId;
            var cookie = new HttpCookie("aCookie")
            {
                Value = profileId.ToString()
            };
            //var cookieValue = Request.Cookies.Get("aCookie").Value;
            Response.Cookies.Add(cookie);
            return Redirect("/Chat/GetChats");
        }

        [HttpGet]
        public ActionResult CreateProfile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateProfile(FormCollection collection)
        {
            var nickname = collection["nickname"];
            var username = collection["username"];
            var email = collection["email"];
            ProfileServiceClient client = new ProfileServiceClient();
            Profile profile = new Profile
            {
                Username = username,
                Nickname = nickname,
                Email = email,
            };
            int i = client.CreateProfile(profile);
            ViewBag.i = i;
            return View();
        }

        [HttpPost]
        public ActionResult LogOut()
        {
            var cookie = Request.Cookies.Get("aCookie");
            if (cookie != null)
            {
                cookie.Expires = DateTime.Now.AddMilliseconds(-1);
                Response.Cookies.Add(cookie);
            }
            return Redirect("/profile/login");
        }
    }
}

project/Project/MVCPresentationTier/Views/Chat/GetChats.cshtml
@{
    ViewBag.Title = "GetChats";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Get chats page</title>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            padding: 15px;
        }
        th {
            text-align: left;
        }
        table tr:nth-child(even) {
            background-color: #eee;
        }
        table tr:nth-child(odd) {
            background-color: #fff;
        }
        table th {
            background-color: black;
            color: white;
        }
        caption {
            text-align: left;
            margin-bottom: 5px;
            text-transform: lowercase;
            font-size: 160%;
            padding: 5px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div>
        <table>
        <caption>Chatrooms</caption>
            <tr>
                <th>Name</th>
                <th>Join</th>
            </tr>
            @foreach (var chat in ViewBag.Chats)
            {
                <tr style="cursor: pointer;">
                    <td onclick="location.href='@Url.Action("GetChat", "Chat", new { chatId = @chat.ActivityId, maxNrOfUsers = @chat.MaxNrOfUsers, name = @chat.Name, profileId = @chat.ProfileId, time = @chat.TimeStamp, type = @chat.Type })'")>@chat.Name</td>
                    <td bgcolor="#00FF00" onclick="window.location.href = '@Url.Action("ChatRoom", "Message", new{ chatId = @chat.ActivityId})';">Join</td>
                </tr>
            }
        </table>
        <br>
        <form action=@Url.Action("GetChats", "Chat") method="post">
            <input type="text" name="searchBy" placeholder="@ViewBag.SearchBy" />
            <input type="submit" />
        </form>
    </div>
</body>
</html>

project/Project/MVCPresentationTier/Views/Message/ChatRoom.cshtml
@{
    ViewBag.Title = "ChatRoom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Chat page</title>
</head>
<body>
    <div>
        <input type="button" id="leaveRoom" value="Leave">
    </div>
    <div class="container">
        <input type="text" id="message" />
        <input type="button" id="sendmessage" value="Send" />
        <input type="hidden" id="chatId" />
        <input type="hidden" id="profileId" />
        <ul id="discussion"></ul>
    </div>
    @section scripts {
        <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
        <script src="~/signalr/hubs"></script>
        <script>
        $(function () {
            var chat = $.connection.messageHub;
            chat.client.addChatMessage = function (name, message) {
                $('#discussion').append('<li><strong>' + htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            $('#chatId').val(@ViewBag.ChatId);
            $('#profileId').val(@ViewBag.ProfileId);
            $.connection.hub.start().done(function () {
                chat.server.joinRoom($('#chatId').val(), $('#profileId').val(), $.connection.hub.id);
                $('#sendmessage').click(function () {
                    chat.server.send($('#chatId').val(), $('#profileId').val(), $('#message').val());
                    $('#message').val('').focus();
                });

                $('#leaveRoom').click(function () {
                    chat.server.leaveRoom($('#chatId').val(), $('#profileId').val(), $.connection.hub.id);
                    $('#message').val('').focus();
                });
            });
        });
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
        </script>
    }
</body>
</html>

project/Project/MVCPresentationTier/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Turakas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Chats", "GetChats", "Chat")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (Request.Cookies.Get("aCookie") != null)
                    {
                        <li class="pointer" onclick="jQuery('#log-out').submit()">Log Out</li>
                        <form action=@Url.Action("LogOut", "Profile") method="post" id="log-out"></form>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Register", "CreateProfile", "Profile")</li>
                        <li>@Html.ActionLink("LogIn", "LogIn", "Profile")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>